export { default as ProfileDashboard } from './profile_dashboard';
export { default as ProfileNotes } from './profile_notes';
export { default as ProfileOtherInformation } from './profile_other_information';
export { default as ProfilePersonalInformation } from './profile_personal_information';
export { default as ProfileProcess } from './profile_tutor_process';
export { default as ProfileProcessOrganization } from './profile_organization_process';
export { default as ProfileSubjectInformation } from './profile_subject_information';
export { default as ProfileAssessments } from "./profile_assessments"
export { default as ProfileSecurity } from './profile_security';
export { default as ProfileChangePassword } from './profile_change_password';
export { default as ProfileKyc } from './profile_kyc';
