export enum Role {
  STUDENT = 'ROLE_STUDENT',
  TUTOR = 'ROLE_TUTOR',
  PARENT = 'ROLE_PARENT',
  ORGANIZATION = 'ROLE_ORGANIZATION',
  ORG_TUTOR = 'ROLE_ORGANIZATION_TUTOR',
  ADMIN = 'ROLE_ADMIN'
}
